### ISSUE TITLE
critical: unable to install Pak on at least Debian bookworm and Ubuntu noble - Error: package or namespace load failed for 'cli' in dyn.load(...):  unable to load shared object ... pak/library/cli/libs/cli.so ... undefined symbol: R_getVarEx

### ISSUE THREAD

**Issue by N0rbert** [r-lib/pak#860]
Steps to reproduce: try to install Pak package on fresh Debian or Ubuntu Docker container

`docker run -it --rm debian:bookworm bash -c "apt-get update && apt-get dist-upgrade -y && apt-get install -y r-base-dev build-essential && apt-cache policy r-base-dev && R --version &&  R -e \"install.packages('pak', repos='http://cran.r-project.org/')\""`

or

`docker run -it --rm ubuntu:noble bash -c "apt-get update && apt-get dist-upgrade -y && apt-get install -y r-base-dev build-essential && apt-cache policy r-base-dev && R --version &&  R -e \"install.packages('pak', repos='http://cran.r-project.org/')\""`

Note: Ubuntu Jammy is also affected.

Expected result: Pak is installed and can load its dynamic libraries or whatever it needs.

Actual result for Debian bookworm:

```
...
r-base-dev:
  Installed: 4.2.2.20221110-2
  Candidate: 4.2.2.20221110-2
  Version table:
 *** 4.2.2.20221110-2 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://deb.debian.org/debian bookworm/main i386 Packages
        100 /var/lib/dpkg/status
...
R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.


R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('pak', repos='http://cran.r-project.org/')
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
trying URL 'http://cran.r-project.org/src/contrib/Transit/pak_0.9.3-1.tar.gz'
Content type 'application/x-gzip' length 3172341 bytes (3.0 MB)
==================================================
downloaded 3.0 MB

* installing *source* package 'pak' ...
** using staged installation
** Running ./configure
** libs
Current platform: x86_64-pc-linux-gnu 
Build platform:   
Target platform:   

Compiling R6 

Compiling cli 
...
make[1]: Leaving directory '/tmp/Rtmpni76Sf/R.INSTALL1fb640fd4b79/pak/src/library/cli/src'
installing to /usr/local/lib/R/site-library/00LOCK-pak/00new/pak/library/cli/libs
Error: package or namespace load failed for 'cli' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/00LOCK-pak/00new/pak/library/cli/libs/cli.so':
  /usr/local/lib/R/site-library/00LOCK-pak/00new/pak/library/cli/libs/cli.so: undefined symbol: R_getVarEx
Error: loading failed
Execution halted
ERROR: loading failed
Error in install_one(pkg, lib = lib) : FAILED
Calls: install_embedded_main -> install_all -> install_one
Execution halted
installing via 'install.libs.R' to /usr/local/lib/R/site-library/00LOCK-pak/00new/pak
Error in eval(ei, envir) : Compilation failed.
* removing '/usr/local/lib/R/site-library/pak'

The downloaded source packages are in
	'/tmp/Rtmp1pQJn1/downloaded_packages'
Warning message:
In install.packages("pak", repos = "http://cran.r-project.org/") :
  installation of package 'pak' had non-zero exit status
> 
```

You should respect the users of stable and supported Linux distros with LTS support!

Also please note that Pak is now a dependency of *devtools* [since 2.5.0 release](https://github.com/r-lib/devtools/releases/tag/v2.5.0), so you should be really careful with `R_getVarEx` and other modern symbols.

**Comment by khammami** [comment]
same here

<details>
  <summary>console output</summary>

  ```
  Error:
  ! ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package pak.
  Full installation output:
  * installing *source* package ‘pak’ ...
  staged installation is only possible with locking
  ** using non-staged installation
  ** Running ./configure
  ** libs
  Current platform: x86_64-pc-linux-gnu 
  Build platform:   
  Target platform:   
  
  Compiling R6 
  
  Compiling cli 
  using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0’
  make[1]: Entering directory '/tmp/RtmpK8KJLR/R.INSTALL1579a2283df44/pak/src/library/cli/src'
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c ansi.c -o ansi.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c cleancall.c -o cleancall.o
  cleancall.c: In function ‘cleancall_init’:
  cleancall.c:39:30: warning: implicit declaration of function ‘R_getVar’; did you mean ‘Rf_setVar’? [-Wimplicit-function-declaration]
     39 |     cleancall_fns_dot_call = R_getVar(Rf_install(".Call"), R_BaseEnv, TRUE);
        |                              ^~~~~~~~
        |                              Rf_setVar
  cleancall.c:39:28: warning: assignment to ‘SEXP’ {aka ‘struct SEXPREC *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
     39 |     cleancall_fns_dot_call = R_getVar(Rf_install(".Call"), R_BaseEnv, TRUE);
        |                            ^
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c diff.c -o diff.o
  diff.c: In function ‘clic_diff_chr’:
  diff.c:104:3: warning: ‘sn’ may be used uninitialized [-Wmaybe-uninitialized]
    104 |   SET_VECTOR_ELT(result, 0, allocVector(INTSXP, sn));
        |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  diff.c:85:7: note: ‘sn’ was declared here
     85 |   int sn;
        |       ^~
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c errors.c -o errors.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c glue.c -o glue.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c init.c -o init.o
  init.c: In function ‘R_init_cli’:
  init.c:113:28: warning: implicit declaration of function ‘R_getVar’; did you mean ‘Rf_setVar’? [-Wimplicit-function-declaration]
    113 |   cleancall_fns_dot_call = R_getVar(Rf_install(".Call"), R_BaseEnv, TRUE);
        |                            ^~~~~~~~
        |                            Rf_setVar
  init.c:113:26: warning: assignment to ‘SEXP’ {aka ‘struct SEXPREC *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
    113 |   cleancall_fns_dot_call = R_getVar(Rf_install(".Call"), R_BaseEnv, TRUE);
        |                          ^
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c inst.c -o inst.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c keypress-unix.c -o keypress-unix.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c keypress-win.c -o keypress-win.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c keypress.c -o keypress.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c md5.c -o md5.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c progress-altrep.c -o progress-altrep.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c progress.c -o progress.o
  progress.c: In function ‘clic__find_var’:
  progress.c:100:16: warning: implicit declaration of function ‘R_getVarEx’ [-Wimplicit-function-declaration]
    100 |     SEXP ret = R_getVarEx(symbol, rho, FALSE, NULL);
        |                ^~~~~~~~~~
  progress.c:100:16: warning: initialization of ‘SEXP’ {aka ‘struct SEXPREC *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c sha1.c -o sha1.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c sha256.c -o sha256.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c thread.c -o thread.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c tty.c -o tty.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c utf8.c -o utf8.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c utils.c -o utils.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c vt.c -o vt.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c vtparse.c -o vtparse.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c vtparse_table.c -o vtparse_table.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c win-utf8.c -o win-utf8.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c winfiles.c -o winfiles.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c xxhash.c -o xxhash.o
  gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include     -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-avGvPq/r-base-4.4.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -pedantic -fdiagnostics-color=always -c xxhash2.c -o xxhash2.o
  gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o cli.so ansi.o cleancall.o diff.o errors.o glue.o init.o inst.o keypress-unix.o keypress-win.o keypress.o md5.o progress-altrep.o progress.o sha1.o sha256.o thread.o tty.o utf8.o utils.o vt.o vtparse.o vtparse_table.o win-utf8.o winfiles.o xxhash.o xxhash2.o -lpthread -L/usr/lib/R/lib -lR
  make[1]: Leaving directory '/tmp/RtmpK8KJLR/R.INSTALL1579a2283df44/pak/src/library/cli/src'
  installing to /tmp/Rtmp096jPo/pkg-lib14e7f5d36f9d5/pak/library/cli/libs
  Error: package or namespace load failed for ‘cli’ in dyn.load(file, DLLpath = DLLpath, ...):
   unable to load shared object '/tmp/Rtmp096jPo/pkg-lib14e7f5d36f9d5/pak/library/cli/libs/cli.so':
    /tmp/Rtmp096jPo/pkg-lib14e7f5d36f9d5/pak/library/cli/libs/cli.so: undefined symbol: R_getVarEx
  Error: loading failed
  Execution halted
  ERROR: loading failed
  Error in install_one(pkg, lib = lib) : FAILED
  Calls: install_embedded_main -> install_all -> install_one
  Execution halted
  installing via 'install.libs.R' to /tmp/Rtmp096jPo/pkg-lib14e7f5d36f9d5/pak
  Error in eval(ei, envir) : Compilation failed.
  * removing ‘/tmp/Rtmp096jPo/pkg-lib14e7f5d36f9d5/pak’
  ```
</details>

in fact, it's happened after updating `devtools` to 2.5.0 yesterday...

> Also please note that Pak is now a dependency of devtools [since 2.5.0 release](https://github.com/r-lib/devtools/releases/tag/v2.5.0), so you should be really careful with R_getVarEx and other modern symbols.

fixed in `devtools` upcoming release 2.5.1 [702c9748fe0cdee18d690aebb52cc813cc98435b](https://github.com/r-lib/devtools/commit/702c9748fe0cdee18d690aebb52cc813cc98435b)

**Comment by gaborcsardi** [comment]
Unfortunately this is because CRAN put out a modified build of pak without telling me (at https://cran.r-project.org/src/contrib/Transit/), and their build needs R 4.5.x at least. 

I am submitting a new release now, so this will be fixed very soon. 

Until then you can try to install the previous version manually, or install from P3M. E.g. on noble:
```
> install.packages("pak", repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")
Installing package into ‘/root/R/x86_64-pc-linux-gnu-library/4.4’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.posit.co/cran/__linux__/noble/latest/src/contrib/pak_0.9.3.tar.gz'
Content type 'binary/octet-stream' length 7032596 bytes (6.7 MB)
==================================================
downloaded 6.7 MB

* installing *binary* package ‘pak’ ...
* DONE (pak)

The downloaded source packages are in
	‘/tmp/RtmpVbm0dP/downloaded_packages’
```

See more at https://packagemanager.posit.co/client/#/repos/cran/setup

**Comment by khammami** [comment]
Thanks @gaborcsardi I have reverted `devtools` to v2.4.6 for now as v2.5.0 point to that modified build of `pak`

**Comment by gaborcsardi** [comment]
@N0rbert Another alternative is to install a pre-built binary, see https://pak.r-lib.org/reference/install.html#pre-built-binaries

**Comment by gaborcsardi** [comment]
New submission happening here: https://github.com/r-lib/pak/issues/862

**Comment by gaborcsardi** [comment]
pak 0.9.4 is on CRAN, so this should be fixed now.

**Comment by N0rbert** [comment]
Just tested 0.9.4 using 

`docker run -it --rm debian:bookworm bash -c "apt-get update && apt-get dist-upgrade -y && apt-get install -y r-base-dev build-essential libcurl4-openssl-dev && apt-cache policy r-base-dev && R --version &&  R -e \"install.packages('pak', repos='http://cran.r-project.org/')\""`

The Pak package is now installed. Thanks!

**Comment by N0rbert** [comment]
Just tested Jammy and Noble, can install Pak 0.9.4 on both of them. 
So bug can be closed.
Thanks!
